import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import SiteHeader from "@/components/navigation/site-header";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
 }: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
        <body
            className={cn(
                `${geistSans.variable} ${geistMono.variable} antialiased`,
                "bg-[#3a314d]",
                "text-white"
            )}
        >
        {}
        <SiteHeader />
        {}
        <main className="pt-20 px-6 md:px-12 max-w-7xl mx-auto">
            {children}
        </main>
        </body>
        </html>
    );
}
